name: Run Django Chef Hub Application
on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: CateringPro_Management_Suite.settings  # Replace with your settings module

    - name: Run Django tests
      run: python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: CateringPro_Management_Suite.settings

    - name: Start Django server
      run: python manage.py runserver &
      env:
        DJANGO_SETTINGS_MODULE: CateringPro_Management_Suite.settings
      # Note: The server runs in the background, but GitHub Actions is not designed for persistent hosting